name: Run new-release script

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '0.0.0'
      profile:
        description: 'Profile to release'
        required: true
        type: choice
        options:
          - web
          - rest-api
          - web-plugin
          - rest-api-plugin
        default: 'rest-api'
      type:
        description: 'Type of release'
        required: true
        type: choice
        options:
          - app
          - plugin
        default: 'app'
      java-version:
        description: 'Java version to use'
        required: true
        type: choice
        options:
          - '11'
          - '17'
          - '21'
        default: '17'

jobs:
  generate_diffs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Java ${{ github.event.inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ github.event.inputs.java-version }}
          distribution: 'zulu'
      
      - name: Install Grails version
        uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f
        id: sdkman
        with:
          candidate: grails
          version: ${{ github.event.inputs.version }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: yarn install
        run: yarn install

      - name: Run new-release script
        run: yarn release -v ${{ github.event.inputs.version }} -p ${{ github.event.inputs.profile }} -t ${{ github.event.inputs.type }} --jdk ${{ github.event.inputs.java-version }}
